### ISSUE TITLE
Voice enabled navigation

### ISSUE THREAD

**Issue by yashk2000** [HarshCasper/HelpingHand#4]
Make tts speak out which page the user is currently on.

**Comment by HarshCasper** [comment]
@all-contributors add please add @agg-shambhavi for code

**Comment by HarshCasper** [comment]
@all-contributors bot please add @agg-shambhavi for code

**Comment by HarshCasper** [comment]
@all-contributors bot please add @agg-shambhavi for idea

**Comment by HarshCasper** [comment]
@all-contributors bot please add @yashk2000 for code

**Comment by HarshCasper** [comment]
@all-contributors bot please add @yashk2000 for documentation

**Comment by HarshCasper** [comment]
@all-contributors bot please add @yashk2000 for idea

**Comment by HarshCasper** [comment]
@all-contributors bot please add @harshcasper for documentation

**Comment by HarshCasper** [comment]
@all-contributors bot please add @harshcasper for code
